### ISSUE TITLE
No need to include `timestamp`, already provided by `clock`

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/substreams-atomicmarket-sales#2]
Substreams provide two native modules:
- block
- clock

which means every map module output already contains everything that's related to **block number & timestamp** by using `clock`.

The `clock` data can be extracted based on which sink needs that information, thus not being required in the map module outputs.

## Scope

- Remove `timestamp` from map modules
- Add `timestamp` to `graph_out` using `clock`

## Example

Using `clock` in `graph_out`

https://github.com/pinax-network/substreams-erc20-supply/blob/48dc84c5eddfe454fd0325c970bea162b1dfed46/src/sink.rs#L8C1-L24C2

**Comment by Pelotfr** [comment]
Refactored with latest commit when writing this comment (https://github.com/pinax-network/substreams-atomicmarket-sales/commit/5ba31bb45352babe4ad6f101e299994f6f7c512c)
