### ISSUE TITLE
Group map modules as `map_block`

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/substreams-atomicmarket-sales#3]
For map modules that require multiple map modules, for performance reasons, it's better to group all the required data into a single map module and name it something like `map_block`

Additionally, in Substreams production mode, the user can only listen to a single map module, which means if there are multiple map modules, it would require a new Substreams connection to listen to the 2nd or 3rd map module. Using this way with all the data within a single map module, it allows the user to listen to that single map module and receive all the data required.

## Scope
- group map modules to single module called `map_block`
  - helper function `map_db_ops`
  - helper function `map_action_traces`

## Example

https://github.com/pinax-network/substreams-erc20/blob/08af80cf5620b0e7a4dca63b2744dbc4c83b6d93/src/maps.rs#L16-L26

```rust
#[substreams::handlers::map]
pub fn map_block(block: Block) -> Result<Erc20Block, Error> {
    let (approvals, transfers) = map_events(&block);
    let storage_changes = map_balance_of(block);

    Ok(Erc20Block {
        approvals,
        transfers,
        storage_changes,
    })
}
```

https://github.com/pinax-network/substreams-erc20/blob/08af80cf5620b0e7a4dca63b2744dbc4c83b6d93/proto/v1/erc20.proto#L5-L9

```proto
message Block {
  repeated ApprovalEvent approvals = 1;
  repeated TransferEvent transfers = 2;
  repeated BalanceOfStorageChange storage_changes = 3;
}
```

**Comment by Pelotfr** [comment]
Very clever way to handle multiple map modules at once.

However, for the final purpose of this substreams I think we can keep the map_sales module as the only map module in it. 

The others module I created were for data exploration regarding the data consistency with AtomicHub.

We can just remove the other map modules and have an even simpler substreams in the end

**Comment by DenisCarriere** [comment]
👍  we can keep `map_sales` as the single map module

As long as there's only a single main map module

Grouping all the data into a single map module and then we can split it afterwards by table in the `graph_out` & `db_out`

**Comment by Pelotfr** [comment]
Removed the unecessary map modules
