### ISSUE TITLE
add SQL `sink` to `substreams.yaml` & `schema.sql`

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/substreams-atomicmarket-sales#4]
## Scope
- [x]  add `sink` metadata to `substreams.yaml`
  - Example: https://github.com/pinax-network/substreams-erc20-contracts/blob/a62bc20530a21b7330c3d553d0ce44bfe9e56f32/substreams.yaml#L82-L87
- [x] add `schema.sql` to repo
  - Example: https://github.com/pinax-network/substreams-erc20-contracts/blob/main/schema.sql

**Comment by Pelotfr** [comment]
Added `schema.sql` and `sink` metadata to the manifest but my new db_out module is not working as intended. Need to investigate further

**Comment by Pelotfr** [comment]
Added the necessary import in the manifest and works fine now, still have the prometheus protobufs unecessarily generated but not a big deal I guess
