### ISSUE TITLE
Updates to `schema.sql`

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/substreams-atomicmarket-sales#5]
Some changes to your SQL schema:
https://github.com/pinax-network/substreams-atomicmarket-sales/blob/master/schema.sql

- [ ] :x:  `id` not required
- [ ] :warning: `sales_id`  should be a number `UInt64` (can also be used as **PRIMARY KEY**)
- [ ] :x:  `timestamp` not required
- [ ] :warning: `trx_id` transaction should be stored as `FixedString(64)`
- [ ] :warning:  `asset_ids` should be an array of `Array(UInt64)` (I think?? @julienrousseau )
- [ ] :warning: `listing_price` should be split up as `listing_price_amount` `Int64` & `listing_price_symcode` `FixedString(7)`
  - [ ] split using https://github.com/pinax-network/antelope.rs
- [ ] :warning: `collection_name` should be defined as EOS Name type, which is maximum 12 characters `FixedString(12)`

Since `sales_id` are unique, we can use `ReplacingMergeTree`

```sql
ENGINE = ReplacingMergeTree
PRIMARY KEY (sales_id)
ORDER BY (sales_id, collection_name, listing_price_symcode, trx_id);
```

We can always add more fields to **ORDER BY**

## References

- https://github.com/pinax-network/substreams-erc20-supply/blob/master/schema.sql
- https://github.com/pinax-network/substreams-sink-clickhouse/blob/main/src/clickhouse/tables/blocks.sql#L7-L9

**Comment by Pelotfr** [comment]
Made the changes with `Float64` for `listing_price_amount` :

https://github.com/pinax-network/substreams-atomicmarket-sales/blob/master/schema.sql

**Comment by Pelotfr** [comment]
Completed the updates in v0.2.0 : https://github.com/pinax-network/substreams-atomicmarket-sales/releases/tag/v0.2.0
